"""Public patiencepilot API."""

from importlib.metadata import PackageNotFoundError, version

from .app import (
    PatiencePilotApp,
    SerializedSession,
    ValidationReport,
    export_session,
    import_session,
    migrate_session_payload,
    validate_session_payload,
    validate_state_payload,
)
from .cards import Card, Color, Rank, Suit, standard_deck
from .engine import apply_move, is_won, legal_moves, new_game, validate_state
from .exceptions import (
    InvalidMoveError,
    InvalidStateError,
    NotationError,
    PatiencePilotError,
    SolverLimitError,
    UnsupportedSolverError,
    UnsupportedVariantError,
)
from .game import GameSession, SessionStep
from .moves import (
    DrawFromStock,
    DrewStockCards,
    MovedCards,
    MoveResult,
    RecycledWaste,
    RecycleWaste,
    RevealedTableauCard,
    TableauToFoundation,
    TableauToTableau,
    WasteToFoundation,
    WasteToTableau,
)
from .notation import (
    SCHEMA_VERSION,
    SerializedGameState,
    SerializedMove,
    SerializedPlayerStackCard,
    SerializedPlayerView,
    SerializedStackCard,
    SerializedUnknownCardConstraints,
    ValidationDiagnostic,
    ValidationResult,
    deserialize_move,
    deserialize_player_view,
    deserialize_state,
    migrate_state_payload,
    move_from_id,
    move_to_id,
    serialize_move,
    serialize_player_view,
    serialize_state,
    state_from_text,
    state_to_text,
    validate_move_id,
    validate_serialized_move,
    validate_serialized_state,
    validate_state_text,
)
from .solvers import (
    DEFAULT_SOLVER_REGISTRY,
    Advice,
    AdviceProvider,
    DummySolver,
    RankedMove,
    SearchLimit,
    Solver,
    SolverDefinition,
    SolverFactory,
    SolverRegistry,
    resolve_solver,
    solver_names,
    visible_klondike_moves,
)
from .state import GameState, StackCard
from .variants import (
    DEFAULT_VARIANT_REGISTRY,
    KlondikeRules,
    Variant,
    VariantDefinition,
    VariantOptions,
    VariantRegistry,
    resolve_state_variant,
    resolve_variant,
    variant_names,
    variant_options_from_state,
)
from .view import PlayerStackCard, PlayerView, UnknownCardConstraints

try:
    __version__ = version("patiencepilot")
except PackageNotFoundError:
    __version__ = "0.0.0+unknown"


__all__ = [
    "DEFAULT_SOLVER_REGISTRY",
    "DEFAULT_VARIANT_REGISTRY",
    "SCHEMA_VERSION",
    "Advice",
    "AdviceProvider",
    "Card",
    "Color",
    "DrawFromStock",
    "DrewStockCards",
    "DummySolver",
    "GameSession",
    "GameState",
    "InvalidMoveError",
    "InvalidStateError",
    "KlondikeRules",
    "MoveResult",
    "MovedCards",
    "NotationError",
    "PatiencePilotApp",
    "PatiencePilotError",
    "PlayerStackCard",
    "PlayerView",
    "Rank",
    "RankedMove",
    "RecycleWaste",
    "RecycledWaste",
    "RevealedTableauCard",
    "SearchLimit",
    "SerializedGameState",
    "SerializedMove",
    "SerializedPlayerStackCard",
    "SerializedPlayerView",
    "SerializedSession",
    "SerializedStackCard",
    "SerializedUnknownCardConstraints",
    "SessionStep",
    "Solver",
    "SolverDefinition",
    "SolverFactory",
    "SolverLimitError",
    "SolverRegistry",
    "StackCard",
    "Suit",
    "TableauToFoundation",
    "TableauToTableau",
    "UnknownCardConstraints",
    "UnsupportedSolverError",
    "UnsupportedVariantError",
    "ValidationDiagnostic",
    "ValidationReport",
    "ValidationResult",
    "Variant",
    "VariantDefinition",
    "VariantOptions",
    "VariantRegistry",
    "WasteToFoundation",
    "WasteToTableau",
    "__version__",
    "apply_move",
    "deserialize_move",
    "deserialize_player_view",
    "deserialize_state",
    "export_session",
    "import_session",
    "is_won",
    "legal_moves",
    "migrate_session_payload",
    "migrate_state_payload",
    "move_from_id",
    "move_to_id",
    "new_game",
    "resolve_solver",
    "resolve_state_variant",
    "resolve_variant",
    "serialize_move",
    "serialize_player_view",
    "serialize_state",
    "solver_names",
    "standard_deck",
    "state_from_text",
    "state_to_text",
    "validate_move_id",
    "validate_serialized_move",
    "validate_serialized_state",
    "validate_session_payload",
    "validate_state",
    "validate_state_payload",
    "validate_state_text",
    "variant_names",
    "variant_options_from_state",
    "visible_klondike_moves",
]
